name: le_fiscaliste_04
description: Application d'optimisation fiscale personnalisée pour les particuliers et professionnels. Analysez votre situation et découvrez comment réduire vos impôts légalement.

version: 1.0.0+1

environment:
  sdk: ^3.7.2
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
    
  # Firebase
  firebase_core: ^2.15.0
  cloud_firestore: ^4.8.4
  firebase_analytics: ^10.4.4
  firebase_performance: ^0.9.2+4
  firebase_auth: ^4.0.0
  
  # UI et interactions
  share_plus: ^7.2.1
  font_awesome_flutter: ^10.7.0
  lottie: ^1.4.3
  confetti: ^0.7.0
  flutter_animate: ^4.2.0
  cached_network_image: ^3.2.3
  
  # SEO et Web
  seo_renderer: ^0.6.0
  url_strategy: ^0.2.0
  
  # Stockage et données
  sqflite: ^2.4.2
  path: ^1.9.1
  shared_preferences: ^2.2.0
  flutter_dotenv: ^5.1.0
  path_provider: ^2.1.5
  
  # Autres utilitaires
  url_launcher: ^6.1.12
  http: ^1.1.0
  provider: ^6.0.5
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - .env
    - assets/images/pattern.png
    - assets/images/user1.webp
    - assets/images/user2.webp
    - assets/images/user3.webp
    - assets/icons/app_icon.png
    - assets/icons/app_icon_foreground.png

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700

flutter_launcher_name:
  name: "Le Fiscaliste"

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  adaptive_icon_background: "#0F1C3F"
  adaptive_icon_foreground: "assets/icons/app_icon_foreground.png"
