name: le_fiscaliste_04
description: Application d'optimisation fiscale personnalisée pour les particuliers et professionnels. Analysez votre situation et découvrez comment réduire vos impôts légalement.
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  adaptive_icon_background: "#0F1C3F"
  adaptive_icon_foreground: "assets/icons/app_icon_foreground.png"
